// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	LoginRequest
	LoginSuccessResponse
	LoginFailedResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Uid              *int32  `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	U1               *int32  `protobuf:"varint,2,req,name=u1" json:"u1,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	WebserviceUuid   *string `protobuf:"bytes,4,req,name=webservice_uuid,json=webserviceUuid" json:"webservice_uuid,omitempty"`
	ChannelId        *int32  `protobuf:"varint,5,req,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LoginRequest) GetU1() int32 {
	if m != nil && m.U1 != nil {
		return *m.U1
	}
	return 0
}

func (m *LoginRequest) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *LoginRequest) GetWebserviceUuid() string {
	if m != nil && m.WebserviceUuid != nil {
		return *m.WebserviceUuid
	}
	return ""
}

func (m *LoginRequest) GetChannelId() int32 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

type LoginSuccessResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginSuccessResponse) Reset()                    { *m = LoginSuccessResponse{} }
func (m *LoginSuccessResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginSuccessResponse) ProtoMessage()               {}
func (*LoginSuccessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginFailedResponse struct {
	Errorcode        *string `protobuf:"bytes,1,req,name=errorcode" json:"errorcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginFailedResponse) Reset()                    { *m = LoginFailedResponse{} }
func (m *LoginFailedResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginFailedResponse) ProtoMessage()               {}
func (*LoginFailedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginFailedResponse) GetErrorcode() string {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginSuccessResponse)(nil), "user.LoginSuccessResponse")
	proto.RegisterType((*LoginFailedResponse)(nil), "user.LoginFailedResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0x2c, 0xdb, 0x83, 0x8e, 0xe2, 0x16, 0xd5, 0x14, 0x0d, 0x2d, 0x18, 0x2f, 0xf5,
	0x54, 0x30, 0x7d, 0x87, 0x42, 0xa1, 0x93, 0x4a, 0x66, 0xe3, 0x48, 0x47, 0x22, 0x62, 0x24, 0x47,
	0xb2, 0x92, 0xb7, 0xc8, 0x33, 0x07, 0x29, 0x09, 0xde, 0xfe, 0xfb, 0x0e, 0x7e, 0x7e, 0x80, 0xe0,
	0xd1, 0x7d, 0xcd, 0xce, 0x2e, 0x96, 0x15, 0x31, 0xb7, 0x97, 0x0c, 0x9e, 0xfe, 0xec, 0x4e, 0x1b,
	0x81, 0xc7, 0x80, 0x7e, 0x61, 0x2f, 0x90, 0x07, 0xad, 0x78, 0xd6, 0x90, 0xae, 0x14, 0x31, 0xb2,
	0x0a, 0x48, 0xe8, 0x39, 0x49, 0x40, 0x42, 0xcf, 0x6a, 0x28, 0x17, 0x7b, 0x40, 0xc3, 0xf3, 0x86,
	0x74, 0x54, 0xdc, 0x0e, 0xf6, 0x09, 0xcf, 0x67, 0xdc, 0x7a, 0x74, 0x27, 0x2d, 0x71, 0x08, 0xb1,
	0xa3, 0x48, 0xff, 0x6a, 0xe5, 0x4d, 0xac, 0xfb, 0x00, 0x90, 0xfb, 0xd1, 0x18, 0x9c, 0x06, 0xad,
	0x78, 0x99, 0x6a, 0xe9, 0x5d, 0x7e, 0x55, 0xfb, 0x06, 0x75, 0xda, 0xf3, 0x1f, 0xa4, 0x44, 0xef,
	0x05, 0xfa, 0xd9, 0x1a, 0x8f, 0xed, 0x37, 0xbc, 0x26, 0xff, 0x19, 0xf5, 0x84, 0xea, 0xc1, 0xec,
	0x1d, 0x28, 0x3a, 0x67, 0x9d, 0xb4, 0x0a, 0xd3, 0x68, 0x2a, 0x56, 0xb8, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x38, 0xb7, 0x0b, 0xf0, 0xf0, 0x00, 0x00, 0x00,
}
